version: '3'

services:
  jenkins:
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    hostname: jenkins
    restart: always





